on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: nimble install -y
      - run: testament p "tests/t*.nim"
  gh-docs:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github Action genshdoc
      - run: nimble gendoc
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
