on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  gh-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"
      - name: "Git Status check"
        run: git status
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - name: Github Action gendoc
        run: nimble gendoc
      - name: rebase gh-pages
        run: |
          git rebase origin/fix_focs
          git push origin gh-pages
          # TODO fix_focs -> master
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0
          git push
